### ISSUE TITLE
Write biomass function

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#1]
It should start with the raw data and have similar options to [RodentAbundances.R](https://github.com/weecology/PortalDataSummaries/blob/master/RodentAbundances.R) but return either biomass or energy.

**Comment by ha0ye** [comment]
I was just thinking about creating time series for the biomass, so I can take a look.

**Comment by ha0ye** [comment]
Oops, I see that @diazrenata already has something like this in her fork. I'm going to see if I can merge that into a new branch.

**Comment by diazrenata** [comment]
I’m wondering about writing tests for these functions...Is it preferable to subset the data and check for specific values (e.g. make sure that the abundance for period 400 sums to 150) or to write more generally, like making sure that there are the right number of columns? Right now I'm doing both, but I don't want to write a bunch of value-specific tests if those are problematic.

I should note, I'm not talking about values that are likely to change as we add new data....They might change if we went back and corrected a chunk from a couple of years ago, but should otherwise be stable.

**Comment by ha0ye** [comment]
I think the basic structure check of "are there the correct columns" is good.
As for testing functionality, the existing tests in test-regression.R that check against digests provides a way to make sure that the output is correct.

**Comment by gmyenni** [comment]
Haha! I was just writing basically what Hao said. So 👍 to that.

You can add your tests to test-regression.R. And as you mentioned, subset the data to a time period that shouldn't change.

And you can start a new test file for structural tests.
