### ISSUE TITLE
Figure out options to get only long-term control plots

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#127]
In the simplest retrieval of the community abundance data, the user might want just the total abundances across the 8 plots 2, 4, 8, 11, 12, 14, 17, 22.
Currently, this doesn't seem non-trivial in the options, because it either returns 15 plots when `length = "all"` or 4 plots when `length = "longterm"`.

Consequently, the user would need to filtere for these plots from the plot-level data, and then filter out the time points where any of the plots are not controls (due to the 2015 plot switch).

**Comment by gmyenni** [comment]
Probably the best thing to do would be to let the user specify what plots they want, since there are many different ways they could define 'long-term,' or who knows what other combination of plots they might be interested in.

We've already got a note in the `filter_plots` function to expand it to filter a specified list of plots. (Because the filtering happens first, then any summary at the treatment or site level would only include the plots the user wants.) So it sounds like it's time to do that.
