### ISSUE TITLE
Weather data cleanup

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#4]
Data cleanup in [Weather.R](https://github.com/weecology/portalr/blob/master/R/Weather.R) is presently non-existent.

- add estimates from regional weather stations to fill in gaps

- possibly replace data flagged as suspect with estimates?

**Comment by gmyenni** [comment]
There is only a short list of regions with missing data:
```R
weather2[which(diff(weather2$timestamp)!=1),1:4]
       year month day hour
20618  1991    10  11 1300
27004  1992     8  28 1600
55423  1995    12  24 1800
55906  1996     1  14 1000
76027  1998     5   2  900
106436 2002     2  10 1200
117830 2004     4  18  800
164688 2009     8  22 1900
217596 2015    10  31  400
217714 2015    11   5  600
217737 2015    11   6  600
217880 2015    11  12  600
217902 2015    11  13  600
217993 2015    11  17  300
218010 2015    11  18  100
218030 2015    11  19  400
218074 2015    11  22  400
218141 2015    12  16  400
218160 2015    12  17  300
218471 2015    12  30  700
219308 2016     2   3  500
```

**Comment by skmorgane** [comment]
Yes, I think Weather.R should be able to provide the data in at least two ways: 1) conservative raw: gaps unfilled, no flagged data. 2) restored (I don't know what else to call it): where we fill in gaps and provide estimates for the flagged data (which may include running that data against regional data to see if the flagged data seems reasonable. If reasonable, we keep, otherwise we use the regional to estimate local). 

There may also be reasons for providing some other combo of gap/flag data, but these seem like the two clear endpoints: 1) let the user decide how they want to fix things and 2) we provide them with how we fix things when we need a complete timeseries.

Of course this requires us to come to consensus on this....
