### ISSUE TITLE
column names 

### ISSUE THREAD

**Issue by emchristensen** [weecology/portalr#40]
column names get changed in the loadData function in data_processing.R -- we should probably just standardize column names across the csv files where possible so this isn't necessary (e.g. in the trapping table Period is capitalized but in the rodent data period is not capitalized)

**Comment by gmyenni** [comment]
The column names in the raw data are stupid (yr, mo, etc.) because they're from the datasheets. It would be nice to change them, and standardize everything as lowercase. But it's going to require a cascade of changes throughout the whole package (and the cleaning functions in PortalData). Are you into it? :)

**Comment by emchristensen** [comment]
I think that would make it easier for outsiders to use our data, and make us look like we have it all together.  Bring it on.

**Comment by gmyenni** [comment]
Yeah, I think we're at a convenient point to do it. And better now than later.

**Comment by gmyenni** [comment]
So I imagine the smart way to go about this is to create a branch in PortalData and change all the column names. Then create a branch over here and make sure we've caught all the column references before merging both. Do you want to start by renaming everything in PortalData?
