### ISSUE TITLE
Document reverse-dependencies in Portal Forecasting

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#72]
Some of the package functions are used in https://github.com/weecology/portalpredictions.

Let's make sure we document what those are here, so that we know what functionality needs to be preserved (or at the very least, what downstream effects to correct for in portal forecasting).

**Comment by ha0ye** [comment]
Hmm, would it be useful to document where they are used? I'd like folks to feel like they can make changes to portalr without worrying unnecessarily about effects on Forecasting.

**Comment by gmyenni** [comment]
Sure. The structure has improved a bit so that it shouldn't be too difficult.
(But also, I think folks shouldn't worry too much. We can just work on getting portalr in its ideal state, and deal with the consequences in forecasting.)

Most uses are in [tools](https://github.com/weecology/portalPredictions/blob/master/tools), especially [prepare_data.R](https://github.com/weecology/portalPredictions/blob/master/tools/prepare_data.R).

The other likely place is the website, especially [the rodent report](https://github.com/weecology/portalPredictions/blob/master/report.Rmd).

**Comment by gmyenni** [comment]
I say not to worry too much not because we shouldn't be proactive about fixing the consequences in forecasting before they become a problem (we should be). I just think that there is a lot of room for the usage, things like
`portalr::download_observations()`,
to be improved by improving portalr. So I anticipate that we'll be breaking a lot of things on purpose.

**Comment by ha0ye** [comment]
Is it possible or even a good idea, to have Travis also generate and push a new docker image for use in PortalPredictions? (@ethanwhite)

**Comment by ha0ye** [comment]
We can also move to a release / dev cycle for `portalr` at ver 1.0 to not keep breaking Portal Forecasting.

**Comment by ethanwhite** [comment]
> Is it possible or even a good idea, to have Travis also generate and push a new docker image for use in PortalPredictions? (@ethanwhite)

Yes, it is possible, but that would mean that if we any breaking changes in `portalr` that it would break `portalPredictions`.

**Comment by ethanwhite** [comment]
Just to clarify - As it is now breaking changes will not break `portalPredictions` specifically because it is running off a container with a version of `portalr` that we know works with the rest of the code base. If we want to update to a newer version of `portalr` we would typically test to make sure it works by running `portalPredictions` locally, and if there are no issues build and push the new docker container. Does that make sense?

**Comment by ethanwhite** [comment]
> We can also move to a release / dev cycle for portalr at ver 1.0 to not keep breaking Portal Forecasting.

There's also no need to wait for 1.0 to do this. We could release 0.1 now and starting iterating from there.

**Comment by ha0ye** [comment]
Ok, it sounds like there's a documented workflow for updating the `portalPredictions` container with `portalr`, so I'm going to close this issue.
