### ISSUE TITLE
imputing biomass for unidentified species

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#86]
re: imputing biomass

There are some species that have `meanwgt = NA` in the species_table, so they don't always get imputed values. I think right now, these all get shoved into the `other` species category with unidentified rodents, but the biomass value ends up as NA because of summing.

Should we have a default weight for "unidentified" or leave this as NA?

**Comment by gmyenni** [comment]
Most things with `meanwgt = NA` in the [species table](https://github.com/weecology/PortalData/blob/master/Rodents/Portal_rodent_species.csv) are species we don't weigh. Biomass for these should be returned as `NA`, as a flag to the user ('you really shouldn't be doing this').

We can probably fill in things like `DX` and `PX` (incompletely identified target rodents) if we reason through some things. There is only one unusually large species of _Dipodomys_ at the site, and it is rare. Likewise, there is only one unusually small species of _Chaetodipus_, and it is rare. So basically, we could get an extremely rough estimate of total weight of `other` rodents, if it's better than nothing.

**Comment by skmorgane** [comment]
To add to @gmyenni ‘s comment, I agree that we can come up with reasonable rules for filling in individuals only identified to genus. If people don’t like our rules then as Ethan suggested they can get the individual data and come up with their own. So the question is, as experienced users of this data, what rules are we comfortable with? Here are some thoughts - but any of the Portal crew should object if they think I’m off: 
1) If someone caught a DS (the really big dipo) they’d know it even if they didn’t get to fully process it and would label it as a DS in the data. I think it safe to say that DX is either merriams or ords and they are similar in size. I’d be comfortable filling all DXs with the average of those species from the data. 
2) PX is trickier, because it could be referencing an unknown perognathus, chaetodipus or peromyscus. There’s only one perognathus and it is very distinctive. If you saw enough to call it a perognathus, you knew what species it was.  I think it likely it would be labeled PF. So PX is probably either a chaetodipus or a peromyscus. This is trickier. In the absence of any measurements I think all we can do is take an average of everything it could be.
3) we could get really hung up on trying to get the best possible estimate (I ran through some convulsed options in my head while writing this note) but it’s important to keep in mind that missing mass but counted individual are relatively rare events and (neotoma, sigmodon, and DS aside) a single individual has little impact on most things we would use the imputed weight for. There’s also only a relatively small difference in body size within a DX or PX group, so the error introduced is again relatively small. So I’m happy with whatever you all think is best.

**Comment by gmyenni** [comment]
Damn, PX could mean _Peromyscus_? Bummer. I have it on the species list as unknown _Chaetodipus_ (meaning, technically, unknown _Chaetodipus_ or _Perognathus_, but since it would be pretty hard to not know you have a PF, probably just unknown _Chaetodipus_).

I mean, it makes sense, since I didn't find another unknown code for _Peromyscus_, and there's no way no one's ever had an unknown _Peromyscus_ in their hands at Portal. Also, it works just fine for biomass, since _Peromyscus_ are kinda smack dab between PP's and PB's anyway.

It's just, you know, a bummer.

**Comment by gmyenni** [comment]
The final thing to consider is `UR`, unidentified target rodent. Even if someone filters for just target rodents (but not just granivores) they will still get this in `other`. So we should provide an estimate. Mean of all rodent weights?

**Comment by skmorgane** [comment]
Concur on the bummer. That's the problem with the 2-letter species codes. A lot of info loss.

for UR, yes I think its the mean mass. We have no info on what that individual was. All we can say with certainty about that individual is that it did not have 0 mass. The only info we have for imputing is the observed distribution of masses at the site, so I think we use the mean mass to infer the most probable  mass of a randomly selected individual, unless someone else thinks they have a more justifiable (but still parsimonious) approach.

**Comment by gmyenni** [comment]
I've updated the species table in [#170](https://github.com/weecology/PortalData/pull/170) over in PortalData.

**Comment by skmorgane** [comment]
I think merging issue #170 takes care of the issue. I'm closing this but @ha0ye feel free to reopen it if I missed something.

**Comment by ha0ye** [comment]
Is it alright to be missing weights for some of the ground squirrels? They show up in the output under "other" occasionally.

**Comment by ethanwhite** [comment]
Ground squirrels aren’t weighed (at least not typically), so yes.
